spring.application.name=zk-template

server.port=8080

spring.main.banner-mode=off

#Database Config
spring.datasource.url=jdbc:postgresql://10.17.134.57:5432/prospect
spring.datasource.username=prospect
spring.datasource.password=prospect
spring.jpa.properties.hibernate.default_schema=zktmp

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate

spring.jpa.properties.hibernate.format_sql=true

#Flyway config
spring.flyway.enabled=false

# Password Hashing Pepper
security.password.pepper=templateSecretPepperKey567!

# SSO Configuration
sso.keycloak.auth-url=http://localhost:8081/realms/demo/protocol/openid-connect/auth
sso.keycloak.token-url=http://localhost:8081/realms/demo/protocol/openid-connect/token
sso.keycloak.userinfo-url=http://localhost:8081/realms/demo/protocol/openid-connect/userinfo
sso.keycloak.client-id=zk-template
sso.keycloak.client-secret=7k5daiHMDkuBJCbfJS4Wkcg8q3jzGtSZ
sso.keycloak.redirect-uri=http://localhost:8080/login/oauth2/code/keycloak